# Configuration hierarchy:
#
# 1. Rubocop defaults
# 2. Carbon Five defaults (this file)
# 3. Project overrides
#
# See http://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-remote-url for details.
#

require: 
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - "config/initializers/secret_token.rb"
    - "db/schema.rb"
    - "db/sample_data.rb"
    - "db/migrate/*.rb"
    - "lib/templates/**/*"
    - "**/node_modules/**/*"
    - "script/rails"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"

#
# Ruby Cops
#

Layout/CaseIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Max: 35
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 250
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Naming/PredicateName:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/HashEachMethods:
  Enabled: true
  
Style/HashTransformKeys: 
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MutableConstant:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/StructInheritance:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

#
# Rails Cops
#

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
