AllCops:
  Exclude:
    - db/migrate/**/*.rb
    - db/schema.rb
    - script/**/*
    - bin/*
    - vendor/bundle/**/*
    - vendor/**/.*



Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/assets.rb
    - config/initializers/secret_token.rb

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
