# Configuration hierarchy:
#
# 1. Rubocop defaults
# 2. Carbon Five defaults (this file)
# 3. Project overrides
#
# See http://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-remote-url for details.
#

require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - rubocop/layout.yml
  - rubocop/lint.yml
  - rubocop/metrics.yml
  - rubocop/naming.yml
  - rubocop/performance.yml
  - rubocop/rails.yml
  - rubocop/security.yml
  - rubocop/style.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - "config/initializers/secret_token.rb"
    - "db/schema.rb"
    - "db/sample_data.rb"
    - "db/migrate/*.rb"
    - "lib/templates/**/*"
    - "**/node_modules/**/*"
    - "script/rails"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"

