version: 2.1
jobs:
  build:
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: cimg/ruby:2.7.6-browsers
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost/selectors_choice_test"
          DISABLE_SPRING: true
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: ubuntu
          BUNDLER_VERSION: 2.1.4
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: selectors_choice_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - selectorschoice-dependencies-v1-{{ checksum "Gemfile.lock" }}
            - selectorschoice-dependencies-v1-
      - run:
          shell: /bin/bash
          name: Machine Setup
          command: |-
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler
      - run:
          shell: /bin/bash
          name: Wait For DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          shell: /bin/bash
          name: Bundle install
          command: |-
            gem list
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
            bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          shell: /bin/bash
          name: DB Setup and Assets compilation
          command: |-
            bundle exec rake db:create db:schema:load db:seed
            bundle exec rake assets:precompile
      - run:
          name: Ruby Tests (rspec)
          command: bundle exec rspec --color --tty --format progress spec
      - save_cache:
          key: selectorschoice-dependencies-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
workflows:
  version: 2.1
  Build and Test:
    jobs:
      - build
